-- ---------------------------------------------------------------------------
-- Additive reserved-username seeds (run in the Supabase SQL editor, any time
-- after forum-profiles.sql). Idempotent: `on conflict (norm) do nothing`, so
-- re-running the whole file is always safe. Append new batches at the bottom
-- with a dated comment — never edit forum-profiles.sql's original seed block
-- (it documents what shipped with the table).
--
-- kind semantics (same as forum-profiles.sql):
--   'blocked' — nobody may take it, ever (owner identity names).
--   'held'    — rejected for ordinary signups; an admin may grant it to the
--               rightful claimant later (owner picks, real-person names).
-- ---------------------------------------------------------------------------

-- 2026-07-21 — owner order (seat 17): reserve "Dirt Jesus".
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('Dirt Jesus'), 'Dirt Jesus', 'held', 'reserved on the owner''s order 2026-07-21')
on conflict (norm) do nothing;

-- 2026-07-21 — Douglas's order (pro-rider reservation pass): MTB downhill (DHI) World Cup, 124 riders.
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('Troy Brosnan'), 'Troy Brosnan', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Henri Kiefer'), 'Henri Kiefer', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Luca Shaw'), 'Luca Shaw', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Loic Bruni'), 'Loic Bruni', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Finn Iles'), 'Finn Iles', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jordan Williams'), 'Jordan Williams', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jackson Goldstone'), 'Jackson Goldstone', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Andreas Kolb'), 'Andreas Kolb', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Felix Griffiths'), 'Felix Griffiths', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Amaury Pierron'), 'Amaury Pierron', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Antoine Pierron'), 'Antoine Pierron', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Loris Vergier'), 'Loris Vergier', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Max Alran'), 'Max Alran', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Till Alran'), 'Till Alran', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Baptiste Pierron'), 'Baptiste Pierron', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Sacha Gabriel Brizin'), 'Sacha Gabriel Brizin', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oriol Cuadrat Castells'), 'Oriol Cuadrat Castells', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Evan Medcalf'), 'Evan Medcalf', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Martin Maes'), 'Martin Maes', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Cole Hulseboch'), 'Cole Hulseboch', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Darragh Ryan'), 'Darragh Ryan', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oliver Zwar'), 'Oliver Zwar', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ronan Dunne'), 'Ronan Dunne', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oli Clark'), 'Oli Clark', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ignacio Garcia Ayora'), 'Ignacio Garcia Ayora', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ryan Pinkerton'), 'Ryan Pinkerton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Richie Rude'), 'Richie Rude', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tyler Waite'), 'Tyler Waite', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jonty Williamson'), 'Jonty Williamson', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Max Hartenstern'), 'Max Hartenstern', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Kasper Hickman'), 'Kasper Hickman', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Alvaro Pestana'), 'Alvaro Pestana', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Lachlan Stevens-McNab'), 'Lachlan Stevens-McNab', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Matt Walker'), 'Matt Walker', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oisin OCallaghan'), 'Oisin OCallaghan', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jack Oliver Davis'), 'Jack Oliver Davis', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Aaron Gwin'), 'Aaron Gwin', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Asa Vermette'), 'Asa Vermette', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Michael Delesalle'), 'Michael Delesalle', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jack McCredie'), 'Jack McCredie', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Danny Hart'), 'Danny Hart', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Greg Minnaar'), 'Greg Minnaar', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Bodhi Kuhn'), 'Bodhi Kuhn', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Joe Breeden'), 'Joe Breeden', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oscar Griffiths'), 'Oscar Griffiths', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Fernando Juan Munoz'), 'Fernando Juan Munoz', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Camden Rutherfurd'), 'Camden Rutherfurd', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Luke Meier-Smith'), 'Luke Meier-Smith', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Remi Thirion'), 'Remi Thirion', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dane Jewett'), 'Dane Jewett', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jakob Jewett'), 'Jakob Jewett', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Thibault Laly'), 'Thibault Laly', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Nathan Pontvianne'), 'Nathan Pontvianne', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Mylann Falquet'), 'Mylann Falquet', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Thomas Estaque'), 'Thomas Estaque', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Raoul Schneeberger'), 'Raoul Schneeberger', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Benoit Coulanges'), 'Benoit Coulanges', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('George Ethan Craik'), 'George Ethan Craik', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Hugo Marini'), 'Hugo Marini', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dakotah Norton'), 'Dakotah Norton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Simon Chapelet'), 'Simon Chapelet', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Filippo Murachelli'), 'Filippo Murachelli', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Davide Palazzari'), 'Davide Palazzari', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dan Atherton'), 'Dan Atherton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gee Atherton'), 'Gee Atherton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Malik Boatwright'), 'Malik Boatwright', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Charlie Hatton'), 'Charlie Hatton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Luke Wayman'), 'Luke Wayman', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Henry Kerr'), 'Henry Kerr', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Stan Nisbet'), 'Stan Nisbet', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Reece Wilson'), 'Reece Wilson', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Bode Burke'), 'Bode Burke', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Alden Pate'), 'Alden Pate', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gavin Tomlinson'), 'Gavin Tomlinson', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Bernard Kerr'), 'Bernard Kerr', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dylan Maples'), 'Dylan Maples', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Roger Vieira'), 'Roger Vieira', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Erik Irmisch'), 'Erik Irmisch', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Hannes Lehmann'), 'Hannes Lehmann', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Matyas Povolny'), 'Matyas Povolny', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tristan Stadlbauer'), 'Tristan Stadlbauer', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Thomas Bruno'), 'Thomas Bruno', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Nick Etherton'), 'Nick Etherton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Sebastian Holguin Villa'), 'Sebastian Holguin Villa', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tuhoto-Ariki Pene'), 'Tuhoto-Ariki Pene', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('David Trummer'), 'David Trummer', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Kasper Woolley'), 'Kasper Woolley', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Marine Cabirou'), 'Marine Cabirou', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Aletha Ostgaard'), 'Aletha Ostgaard', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Valentina Holl'), 'Valentina Holl', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Lisa Baumann'), 'Lisa Baumann', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tilly Boadle'), 'Tilly Boadle', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Myriam Nicole'), 'Myriam Nicole', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Nina Hoffmann'), 'Nina Hoffmann', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Eliana Hulseboch'), 'Eliana Hulseboch', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tahnee Seagrave'), 'Tahnee Seagrave', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Kaos Seagrave'), 'Kaos Seagrave', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Phoebe Gale'), 'Phoebe Gale', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Illy Morrison'), 'Illy Morrison', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Rosa Zierl'), 'Rosa Zierl', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Matilda Melton'), 'Matilda Melton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jess Blewitt'), 'Jess Blewitt', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Vicky Clavel'), 'Vicky Clavel', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Veronika Widmann'), 'Veronika Widmann', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Rachel Atherton'), 'Rachel Atherton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Elise Empey'), 'Elise Empey', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Harriet Harnden'), 'Harriet Harnden', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Frida Helena Ronning'), 'Frida Helena Ronning', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jenna Hastings'), 'Jenna Hastings', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Louise-Anna Ferguson'), 'Louise-Anna Ferguson', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Mille Johnset'), 'Mille Johnset', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gracey Hemstreet'), 'Gracey Hemstreet', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Lina Frener'), 'Lina Frener', 'held', 'MTB downhill (DHI) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Anna Newkirk'), 'Anna Newkirk', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Raina Logar'), 'Raina Logar', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Zanna Logar'), 'Zanna Logar', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Lisa Bouladou'), 'Lisa Bouladou', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Rebecca Bruno'), 'Rebecca Bruno', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Eleonora Farina'), 'Eleonora Farina', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Valentina Roa Sanchez'), 'Valentina Roa Sanchez', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gloria Scarsi'), 'Gloria Scarsi', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ava Chaumet Lagrange'), 'Ava Chaumet Lagrange', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Rosa Marie Jensen'), 'Rosa Marie Jensen', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Sacha Earnest'), 'Sacha Earnest', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season')
on conflict (norm) do nothing;
