-- ---------------------------------------------------------------------------
-- Additive reserved-username seeds (run in the Supabase SQL editor, any time
-- after forum-profiles.sql). Idempotent: `on conflict (norm) do nothing`, so
-- re-running the whole file is always safe. Append new batches at the bottom
-- with a dated comment — never edit forum-profiles.sql's original seed block
-- (it documents what shipped with the table).
--
-- kind semantics (same as forum-profiles.sql):
--   'blocked' — nobody may take it, ever (owner identity names).
--   'held'    — rejected for ordinary signups; an admin may grant it to the
--               rightful claimant later (owner picks, real-person names).
-- ---------------------------------------------------------------------------

-- 2026-07-21 — owner order (seat 17): reserve "Dirt Jesus".
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('Dirt Jesus'), 'Dirt Jesus', 'held', 'reserved on the owner''s order 2026-07-21')
on conflict (norm) do nothing;

-- 2026-07-21 — Douglas's order (pro-rider reservation pass): MTB downhill (DHI) World Cup, 124 riders.
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('Troy Brosnan'), 'Troy Brosnan', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Henri Kiefer'), 'Henri Kiefer', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Luca Shaw'), 'Luca Shaw', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Loic Bruni'), 'Loic Bruni', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Finn Iles'), 'Finn Iles', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jordan Williams'), 'Jordan Williams', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jackson Goldstone'), 'Jackson Goldstone', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Andreas Kolb'), 'Andreas Kolb', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Felix Griffiths'), 'Felix Griffiths', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Amaury Pierron'), 'Amaury Pierron', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Antoine Pierron'), 'Antoine Pierron', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Loris Vergier'), 'Loris Vergier', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Max Alran'), 'Max Alran', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Till Alran'), 'Till Alran', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Baptiste Pierron'), 'Baptiste Pierron', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Sacha Gabriel Brizin'), 'Sacha Gabriel Brizin', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oriol Cuadrat Castells'), 'Oriol Cuadrat Castells', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Evan Medcalf'), 'Evan Medcalf', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Martin Maes'), 'Martin Maes', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Cole Hulseboch'), 'Cole Hulseboch', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Darragh Ryan'), 'Darragh Ryan', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oliver Zwar'), 'Oliver Zwar', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ronan Dunne'), 'Ronan Dunne', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oli Clark'), 'Oli Clark', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ignacio Garcia Ayora'), 'Ignacio Garcia Ayora', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ryan Pinkerton'), 'Ryan Pinkerton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Richie Rude'), 'Richie Rude', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tyler Waite'), 'Tyler Waite', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jonty Williamson'), 'Jonty Williamson', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Max Hartenstern'), 'Max Hartenstern', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Kasper Hickman'), 'Kasper Hickman', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Alvaro Pestana'), 'Alvaro Pestana', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Lachlan Stevens-McNab'), 'Lachlan Stevens-McNab', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Matt Walker'), 'Matt Walker', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oisin OCallaghan'), 'Oisin OCallaghan', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jack Oliver Davis'), 'Jack Oliver Davis', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Aaron Gwin'), 'Aaron Gwin', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Asa Vermette'), 'Asa Vermette', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Michael Delesalle'), 'Michael Delesalle', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jack McCredie'), 'Jack McCredie', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Danny Hart'), 'Danny Hart', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Greg Minnaar'), 'Greg Minnaar', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Bodhi Kuhn'), 'Bodhi Kuhn', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Joe Breeden'), 'Joe Breeden', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Oscar Griffiths'), 'Oscar Griffiths', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Fernando Juan Munoz'), 'Fernando Juan Munoz', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Camden Rutherfurd'), 'Camden Rutherfurd', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Luke Meier-Smith'), 'Luke Meier-Smith', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Remi Thirion'), 'Remi Thirion', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dane Jewett'), 'Dane Jewett', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jakob Jewett'), 'Jakob Jewett', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Thibault Laly'), 'Thibault Laly', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Nathan Pontvianne'), 'Nathan Pontvianne', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Mylann Falquet'), 'Mylann Falquet', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Thomas Estaque'), 'Thomas Estaque', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Raoul Schneeberger'), 'Raoul Schneeberger', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Benoit Coulanges'), 'Benoit Coulanges', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('George Ethan Craik'), 'George Ethan Craik', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Hugo Marini'), 'Hugo Marini', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dakotah Norton'), 'Dakotah Norton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Simon Chapelet'), 'Simon Chapelet', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Filippo Murachelli'), 'Filippo Murachelli', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Davide Palazzari'), 'Davide Palazzari', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dan Atherton'), 'Dan Atherton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gee Atherton'), 'Gee Atherton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Malik Boatwright'), 'Malik Boatwright', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Charlie Hatton'), 'Charlie Hatton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Luke Wayman'), 'Luke Wayman', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Henry Kerr'), 'Henry Kerr', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Stan Nisbet'), 'Stan Nisbet', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Reece Wilson'), 'Reece Wilson', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Bode Burke'), 'Bode Burke', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Alden Pate'), 'Alden Pate', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gavin Tomlinson'), 'Gavin Tomlinson', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Bernard Kerr'), 'Bernard Kerr', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dylan Maples'), 'Dylan Maples', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Roger Vieira'), 'Roger Vieira', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Erik Irmisch'), 'Erik Irmisch', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Hannes Lehmann'), 'Hannes Lehmann', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Matyas Povolny'), 'Matyas Povolny', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tristan Stadlbauer'), 'Tristan Stadlbauer', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Thomas Bruno'), 'Thomas Bruno', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Nick Etherton'), 'Nick Etherton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Sebastian Holguin Villa'), 'Sebastian Holguin Villa', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tuhoto-Ariki Pene'), 'Tuhoto-Ariki Pene', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('David Trummer'), 'David Trummer', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Kasper Woolley'), 'Kasper Woolley', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Marine Cabirou'), 'Marine Cabirou', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Aletha Ostgaard'), 'Aletha Ostgaard', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Valentina Holl'), 'Valentina Holl', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Lisa Baumann'), 'Lisa Baumann', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tilly Boadle'), 'Tilly Boadle', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Myriam Nicole'), 'Myriam Nicole', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Nina Hoffmann'), 'Nina Hoffmann', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Eliana Hulseboch'), 'Eliana Hulseboch', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tahnee Seagrave'), 'Tahnee Seagrave', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Kaos Seagrave'), 'Kaos Seagrave', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Phoebe Gale'), 'Phoebe Gale', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Illy Morrison'), 'Illy Morrison', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Rosa Zierl'), 'Rosa Zierl', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Matilda Melton'), 'Matilda Melton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jess Blewitt'), 'Jess Blewitt', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Vicky Clavel'), 'Vicky Clavel', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Veronika Widmann'), 'Veronika Widmann', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Rachel Atherton'), 'Rachel Atherton', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Elise Empey'), 'Elise Empey', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Harriet Harnden'), 'Harriet Harnden', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Frida Helena Ronning'), 'Frida Helena Ronning', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jenna Hastings'), 'Jenna Hastings', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Louise-Anna Ferguson'), 'Louise-Anna Ferguson', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Mille Johnset'), 'Mille Johnset', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gracey Hemstreet'), 'Gracey Hemstreet', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Lina Frener'), 'Lina Frener', 'held', 'MTB downhill (DHI) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Anna Newkirk'), 'Anna Newkirk', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Raina Logar'), 'Raina Logar', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Zanna Logar'), 'Zanna Logar', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Lisa Bouladou'), 'Lisa Bouladou', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Rebecca Bruno'), 'Rebecca Bruno', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Eleonora Farina'), 'Eleonora Farina', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Valentina Roa Sanchez'), 'Valentina Roa Sanchez', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gloria Scarsi'), 'Gloria Scarsi', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ava Chaumet Lagrange'), 'Ava Chaumet Lagrange', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Rosa Marie Jensen'), 'Rosa Marie Jensen', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Sacha Earnest'), 'Sacha Earnest', 'held', 'MTB downhill (DHI) World Cup pro — pinkbike.com, 2026 season')
on conflict (norm) do nothing;

-- 2026-07-21 — Douglas's order (pro-rider reservation pass): MTB enduro (EDR) World Cup, 49 riders.
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('Tristan Botteram'), 'Tristan Botteram', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Tommaso Calonaci'), 'Tommaso Calonaci', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Tommaso Francardo'), 'Tommaso Francardo', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Lief Rodgers'), 'Lief Rodgers', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Alex Rudeau'), 'Alex Rudeau', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Evan Wall'), 'Evan Wall', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Vojtech Blaha'), 'Vojtech Blaha', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Marius Tenet Berrat'), 'Marius Tenet Berrat', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Tarmo Ryynanen'), 'Tarmo Ryynanen', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Raphael Giambi'), 'Raphael Giambi', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Slawomir Lukasik'), 'Slawomir Lukasik', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Adrien Dailly'), 'Adrien Dailly', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Jt Fisher'), 'Jt Fisher', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Ryan Gilchrist'), 'Ryan Gilchrist', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Gregory Callaghan'), 'Gregory Callaghan', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Moritz Silberhorn'), 'Moritz Silberhorn', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Marco Osborne'), 'Marco Osborne', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Emmett Hancock'), 'Emmett Hancock', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Max Pfeil'), 'Max Pfeil', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Jakub Pivnicka'), 'Jakub Pivnicka', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Dimitri Tordo'), 'Dimitri Tordo', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Iago Garay Tamayo'), 'Iago Garay Tamayo', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Albin Cambos'), 'Albin Cambos', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('William Brodie'), 'William Brodie', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Gabriel Sainthuile'), 'Gabriel Sainthuile', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Zakarias Blom Johansen'), 'Zakarias Blom Johansen', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Alexis Icardo'), 'Alexis Icardo', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Melanie Pugin'), 'Melanie Pugin', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Ella Conolly'), 'Ella Conolly', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Winnifred Goldsbury'), 'Winnifred Goldsbury', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Elly Hoskin'), 'Elly Hoskin', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Raphaela Richter'), 'Raphaela Richter', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Nadine Ellecosta'), 'Nadine Ellecosta', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('George Swift'), 'George Swift', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Simona Kuchynkova'), 'Simona Kuchynkova', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Rebecca Baraona'), 'Rebecca Baraona', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Helen Weber'), 'Helen Weber', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Hannah Gillcrist'), 'Hannah Gillcrist', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Chloe Taylor'), 'Chloe Taylor', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Geza Rodgers'), 'Geza Rodgers', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Julie Duvert'), 'Julie Duvert', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Clarissa Carzolio'), 'Clarissa Carzolio', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Morgane Charre'), 'Morgane Charre', 'held', 'MTB enduro (EDR) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Romy Williams'), 'Romy Williams', 'held', 'MTB enduro (EDR) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Matteo Falcini'), 'Matteo Falcini', 'held', 'MTB enduro (EDR) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('William Scheele'), 'William Scheele', 'held', 'MTB enduro (EDR) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gustav Wildhaber'), 'Gustav Wildhaber', 'held', 'MTB enduro (EDR) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Louison Arnaud'), 'Louison Arnaud', 'held', 'MTB enduro (EDR) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ivan Williams'), 'Ivan Williams', 'held', 'MTB enduro (EDR) World Cup pro — pinkbike.com, 2026 season')
on conflict (norm) do nothing;

-- 2026-07-21 — Douglas's order (pro-rider reservation pass): MTB cross-country (XCO) World Cup, 72 riders.
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('Adrien Boichis'), 'Adrien Boichis', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Martin Vidaurre Kossmann'), 'Martin Vidaurre Kossmann', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Christopher Blevins'), 'Christopher Blevins', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Victor Koretzky'), 'Victor Koretzky', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Anton Cooper'), 'Anton Cooper', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Tobias Lillelund'), 'Tobias Lillelund', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Filippo Colombo'), 'Filippo Colombo', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Fabio Puntener'), 'Fabio Puntener', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Bjorn Riley'), 'Bjorn Riley', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Andri Frischknecht'), 'Andri Frischknecht', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Nino Schurter'), 'Nino Schurter', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Mathis Azzaro'), 'Mathis Azzaro', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Knut Rohme'), 'Knut Rohme', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Nael Rouffiac'), 'Nael Rouffiac', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Joshua Dubau'), 'Joshua Dubau', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('David List'), 'David List', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Luca Martin'), 'Luca Martin', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Charlie Aldridge'), 'Charlie Aldridge', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Cole Punchard'), 'Cole Punchard', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Luca Schwarzbauer'), 'Luca Schwarzbauer', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Riley Amos'), 'Riley Amos', 'held', 'MTB cross-country (XCO) World Cup pro — racing.trekbikes.com, 2026 season'),
  (public.profile_norm('Vlad Dascalu'), 'Vlad Dascalu', 'held', 'MTB cross-country (XCO) World Cup pro — racing.trekbikes.com, 2026 season'),
  (public.profile_norm('Juri Zanotti'), 'Juri Zanotti', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Luca Braidot'), 'Luca Braidot', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Lars Forster'), 'Lars Forster', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Mathias Fluckiger'), 'Mathias Fluckiger', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Vital Albin'), 'Vital Albin', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Dario Lillo'), 'Dario Lillo', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Carter Woods'), 'Carter Woods', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Jens Schuermans'), 'Jens Schuermans', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Alan Hatherly'), 'Alan Hatherly', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Simon Andreassen'), 'Simon Andreassen', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Ondrej Cink'), 'Ondrej Cink', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Julian Schelb'), 'Julian Schelb', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Jofre Cullell Estape'), 'Jofre Cullell Estape', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Luca Schatti'), 'Luca Schatti', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Samuel Gaze'), 'Samuel Gaze', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jordan Sarrou'), 'Jordan Sarrou', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Thomas Pidcock'), 'Thomas Pidcock', 'held', 'MTB cross-country (XCO) World Cup pro — xcodata.com, 2026 season'),
  (public.profile_norm('Laura Stigger'), 'Laura Stigger', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Sina Frei'), 'Sina Frei', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Haley Batten'), 'Haley Batten', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Nicole Koller'), 'Nicole Koller', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Caroline Bohe'), 'Caroline Bohe', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Anne Terpstra'), 'Anne Terpstra', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Martina Berta'), 'Martina Berta', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Ronja Eibl'), 'Ronja Eibl', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Savilia Blunk'), 'Savilia Blunk', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Greta Seiwald'), 'Greta Seiwald', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Jolanda Neff'), 'Jolanda Neff', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ana Santos'), 'Ana Santos', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Jenny Rissveds'), 'Jenny Rissveds', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Valentina Corvi'), 'Valentina Corvi', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Gwendalyn Gibson'), 'Gwendalyn Gibson', 'held', 'MTB cross-country (XCO) World Cup pro — racing.trekbikes.com, 2026 season'),
  (public.profile_norm('Nina Graf'), 'Nina Graf', 'held', 'MTB cross-country (XCO) World Cup pro — racing.trekbikes.com, 2026 season'),
  (public.profile_norm('Evie Richards'), 'Evie Richards', 'held', 'MTB cross-country (XCO) World Cup pro — racing.trekbikes.com, 2026 season'),
  (public.profile_norm('Isabella Holmgren'), 'Isabella Holmgren', 'held', 'MTB cross-country (XCO) World Cup pro — mtbdata.com, 2026 season'),
  (public.profile_norm('Heby Sofie Pedersen'), 'Heby Sofie Pedersen', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Ella Macphee'), 'Ella Macphee', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Alessandra Keller'), 'Alessandra Keller', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Jennifer Jackson'), 'Jennifer Jackson', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Rebecca Henderson'), 'Rebecca Henderson', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Kira Bohm'), 'Kira Bohm', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Kelsey Urban'), 'Kelsey Urban', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Carla Hahn'), 'Carla Hahn', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Chiara Teocchi'), 'Chiara Teocchi', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Ramona Forchini'), 'Ramona Forchini', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Mona Mitterwallner'), 'Mona Mitterwallner', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Puck Pieterse'), 'Puck Pieterse', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Loana Lecomte'), 'Loana Lecomte', 'held', 'MTB cross-country (XCO) World Cup pro — pinkbike.com, 2026 season'),
  (public.profile_norm('Ronja Blochlinger'), 'Ronja Blochlinger', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season'),
  (public.profile_norm('Madigan Munro'), 'Madigan Munro', 'held', 'MTB cross-country (XCO) World Cup pro — ucimtbworldseries.com, 2026 season')
on conflict (norm) do nothing;
