-- ---------------------------------------------------------------------------
-- Reserved-username seeds: manufacturer brand names + prominent MTB/cycling
-- influencers/creators (run in the Supabase SQL editor, any time after
-- forum-profiles.sql). Idempotent: `on conflict (norm) do nothing`, so
-- re-running the whole file is always safe. Sibling to
-- forum-reserved-additions.sql (that file is owned by a parallel worker —
-- this file never touches it). Append new batches at the bottom with a dated
-- comment, same convention as forum-reserved-additions.sql.
--
-- kind semantics (same as forum-profiles.sql): every row here is 'held' —
-- rejected for ordinary signups; an admin may grant it to the rightful
-- claimant later (a manufacturer's own rep, or the creator themselves).
--
-- `label` is deliberately the SHAPE-LEGAL form of each name (matches the
-- profiles CHECK, [A-Za-z0-9 _-]{3,24}), NOT always the raw catalog/brand
-- string — profile_norm() only strips spaces/underscores/hyphens, so a label
-- carrying an illegal character (an apostrophe, an asterisk, a diacritic)
-- would normalize to a value no real (CHECK-constrained) username could ever
-- reach, making the reservation silently inert. Where a name needed cleanup,
-- the `note` records the original spelling for provenance.
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- BATCH 1 — 2026-07-21 (owner order, seat: brand-influencer-reserve worker):
-- manufacturer names, extracted from every distinct `brand:` field across
-- ALL catalog files (src/compat.js PARTS, src/kit.js, data/bmx.js,
-- data/road.js, data/gravel.js, data/emtb.js, data/striders.js), deduped
-- case-insensitively. 384 rows (383 distinct brands + one explicit space
-- variant for e*thirteen, see below).
--
-- Skipped (reported, not fabricated — see the worker's final report for the
-- full reasoning):
--   * Under-3-char brands that stay under 3 chars even after stripping
--     illegal characters (the shape forbids padding): GT, HT, KS, VP, YT,
--     3T, and S&M (strips to "SM", 2 chars).
--   * "100%" — stripping the '%' leaves only the bare number "100", which
--     loses all brand-identifying signal and would reserve an overly generic
--     numeric string unrelated to the brand as written. Judgment call, not a
--     shape failure; flagged for Douglas to override if he'd rather have it.
-- ===========================================================================
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('7iDP'), '7iDP', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('7mesh'), '7mesh', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('9point8'), '9point8', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Abus'), 'Abus', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('ACID'), 'ACID', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Acros'), 'Acros', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Adidas'), 'Adidas', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Airdrop'), 'Airdrop', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Alex Rims'), 'Alex Rims', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Alexrims'), 'Alexrims', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Alienation'), 'Alienation', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('All-City'), 'All-City', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Allied'), 'Allied', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Alpina'), 'Alpina', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Alpinestars'), 'Alpinestars', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Alutech'), 'Alutech', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Answer'), 'Answer', 'held', 'manufacturer name — Kit, MTB catalogs'),
  (public.profile_norm('Antidote'), 'Antidote', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('ANVL'), 'ANVL', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Ari'), 'Ari', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Atherton'), 'Atherton', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Atlas'), 'Atlas', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Avid'), 'Avid', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Banshee'), 'Banshee', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Banwood'), 'Banwood', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Bell'), 'Bell', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Bianchi'), 'Bianchi', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('BikeYoke'), 'BikeYoke', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Bird'), 'Bird', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Bixe'), 'Bixe', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Black Ops'), 'Black Ops', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Bliss'), 'Bliss', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Bliss Protection'), 'Bliss Protection', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Bliz'), 'Bliz', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Bluegrass'), 'Bluegrass', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('BMC'), 'BMC', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Bolle'), 'Bolle', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Bombtrack'), 'Bombtrack', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Bontrager'), 'Bontrager', 'held', 'manufacturer name — Gravel, Kit, MTB catalogs'),
  (public.profile_norm('Box'), 'Box', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Brand-X'), 'Brand-X', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Brooks'), 'Brooks', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('BSD'), 'BSD', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Burgtec'), 'Burgtec', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Cairn'), 'Cairn', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Campagnolo'), 'Campagnolo', 'held', 'manufacturer name — Gravel, Road catalogs'),
  (public.profile_norm('Cane Creek'), 'Cane Creek', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Canfield'), 'Canfield', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Cannondale'), 'Cannondale', 'held', 'manufacturer name — EMTB, Gravel, MTB, Road, Striders catalogs'),
  (public.profile_norm('Canyon'), 'Canyon', 'held', 'manufacturer name — EMTB, Gravel, MTB, Road catalogs'),
  (public.profile_norm('Cervelo'), 'Cervelo', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Chase'), 'Chase', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Chillafish'), 'Chillafish', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Chris King'), 'Chris King', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Chromag'), 'Chromag', 'held', 'manufacturer name — Kit, MTB catalogs'),
  (public.profile_norm('Cinelli'), 'Cinelli', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Clarks'), 'Clarks', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Club Ride'), 'Club Ride', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Club Ride Apparel'), 'Club Ride Apparel', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Co-op Cycles'), 'Co-op Cycles', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Colony'), 'Colony', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Columbus'), 'Columbus', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Commencal'), 'Commencal', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('Continental'), 'Continental', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Contra'), 'Contra', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Cotic'), 'Cotic', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Crankbrothers'), 'Crankbrothers', 'held', 'manufacturer name — Gravel, Kit, MTB catalogs'),
  (public.profile_norm('CST'), 'CST', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Cube'), 'Cube', 'held', 'manufacturer name — EMTB, Kit, MTB catalogs'),
  (public.profile_norm('Cult'), 'Cult', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Dainese'), 'Dainese', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Dakine'), 'Dakine', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Deda'), 'Deda', 'held', 'manufacturer name — Gravel, Road catalogs'),
  (public.profile_norm('Deity'), 'Deity', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Delium'), 'Delium', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Demon'), 'Demon', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Demon United'), 'Demon United', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('DEUX'), 'DEUX', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Deviate'), 'Deviate', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Devinci'), 'Devinci', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('DHaRCO'), 'DHaRCO', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Dia-Compe'), 'Dia-Compe', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Diamondback'), 'Diamondback', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('DMR'), 'DMR', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Dragon Alliance'), 'Dragon Alliance', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('DT Swiss'), 'DT Swiss', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('DTS Geardrive'), 'DTS Geardrive', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('DUO Brand'), 'DUO Brand', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('DVO'), 'DVO', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('ethirteen'), 'ethirteen', 'held', 'manufacturer name — MTB catalog (cleaned from ''e*thirteen'')'),
  (public.profile_norm('e thirteen'), 'e thirteen', 'held', 'manufacturer name — MTB catalog (space variant of ''e*thirteen''; collapses to the same norm as ''ethirteen'', kept for explicit coverage)'),
  (public.profile_norm('Early Rider'), 'Early Rider', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Easton'), 'Easton', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Eclat'), 'Eclat', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Eightpins'), 'Eightpins', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('EKS Brand'), 'EKS Brand', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Endura'), 'Endura', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Entity'), 'Entity', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('ENVE'), 'ENVE', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Ergon'), 'Ergon', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('ESI'), 'ESI', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Evil'), 'Evil', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('EVOC'), 'EVOC', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('EVS'), 'EVS', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('EVS Sports'), 'EVS Sports', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('EXT'), 'EXT', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Fabric'), 'Fabric', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Fairlight'), 'Fairlight', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Fasthouse'), 'Fasthouse', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Fiend'), 'Fiend', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Fist Handwear'), 'Fist Handwear', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Fit Bike Co'), 'Fit Bike Co', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Five Ten'), 'Five Ten', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Fizik'), 'Fizik', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Fly Bikes'), 'Fly Bikes', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Fly Racing'), 'Fly Racing', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Focus'), 'Focus', 'held', 'manufacturer name — EMTB, Gravel, MTB catalogs'),
  (public.profile_norm('Forbidden'), 'Forbidden', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Formula'), 'Formula', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Fox'), 'Fox', 'held', 'manufacturer name — Gravel, Kit, MTB catalogs'),
  (public.profile_norm('Frameworks'), 'Frameworks', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Frog'), 'Frog', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('FSA'), 'FSA', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Fuji'), 'Fuji', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Fulcrum'), 'Fulcrum', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Funn'), 'Funn', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('G-Form'), 'G-Form', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Galfer'), 'Galfer', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Garbaruk'), 'Garbaruk', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Gatorz'), 'Gatorz', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Generic'), 'Generic', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Genesis'), 'Genesis', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Geometron'), 'Geometron', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Ghost'), 'Ghost', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Giant'), 'Giant', 'held', 'manufacturer name — EMTB, Gravel, Kit, MTB, Road, Striders catalogs'),
  (public.profile_norm('Giro'), 'Giro', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Goodyear'), 'Goodyear', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Gore Wear'), 'Gore Wear', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Ground Fiftyone'), 'Ground Fiftyone', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Guardian'), 'Guardian', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Haibike'), 'Haibike', 'held', 'manufacturer name — EMTB catalog'),
  (public.profile_norm('Halo'), 'Halo', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Handup'), 'Handup', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Haro'), 'Haro', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Hayes'), 'Hayes', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Hope'), 'Hope', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('HT Components'), 'HT Components', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Hunt'), 'Hunt', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Hutchinson'), 'Hutchinson', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Ibis'), 'Ibis', 'held', 'manufacturer name — EMTB, Gravel, MTB catalogs'),
  (public.profile_norm('Industry Nine'), 'Industry Nine', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Intend'), 'Intend', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Intense'), 'Intense', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('ION'), 'ION', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Iridium'), 'Iridium', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('iXS'), 'iXS', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Jamis'), 'Jamis', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Jien-Yuan'), 'Jien-Yuan', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Julbo'), 'Julbo', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Kali Protectives'), 'Kali Protectives', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Kenda'), 'Kenda', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Kinderfeets'), 'Kinderfeets', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('KindShock'), 'KindShock', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Kink'), 'Kink', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('KMC'), 'KMC', 'held', 'manufacturer name — BMX, MTB catalogs'),
  (public.profile_norm('Knolly'), 'Knolly', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Kogel'), 'Kogel', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Kokua'), 'Kokua', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Kona'), 'Kona', 'held', 'manufacturer name — EMTB, Gravel, MTB catalogs'),
  (public.profile_norm('KUbikes'), 'KUbikes', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Last'), 'Last', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Lauf'), 'Lauf', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Lazer'), 'Lazer', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Leatt'), 'Leatt', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('LittleBig'), 'LittleBig', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Liv'), 'Liv', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Lizard Skins'), 'Lizard Skins', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Look'), 'Look', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Loose Riders'), 'Loose Riders', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Madison'), 'Madison', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Magura'), 'Magura', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Manitou'), 'Manitou', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Mankind'), 'Mankind', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Marin'), 'Marin', 'held', 'manufacturer name — EMTB, Gravel, MTB catalogs'),
  (public.profile_norm('Marzocchi'), 'Marzocchi', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Mason'), 'Mason', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Mavic'), 'Mavic', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Maxxis'), 'Maxxis', 'held', 'manufacturer name — BMX, Gravel, MTB catalogs'),
  (public.profile_norm('Melon Optics'), 'Melon Optics', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Merida'), 'Merida', 'held', 'manufacturer name — EMTB, Gravel, MTB catalogs'),
  (public.profile_norm('Merritt'), 'Merritt', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('MET'), 'MET', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Michelin'), 'Michelin', 'held', 'manufacturer name — MTB, Road catalogs'),
  (public.profile_norm('microSHIFT'), 'microSHIFT', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Mondraker'), 'Mondraker', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('Mongoose'), 'Mongoose', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Mons Royale'), 'Mons Royale', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Moots'), 'Moots', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Moustache'), 'Moustache', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('MRP'), 'MRP', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Native Eyewear'), 'Native Eyewear', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Natural Fit'), 'Natural Fit', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Newmen'), 'Newmen', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Nicolai'), 'Nicolai', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Niner'), 'Niner', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Norco'), 'Norco', 'held', 'manufacturer name — EMTB, Gravel, MTB catalogs'),
  (public.profile_norm('Norrona'), 'Norrona', 'held', 'manufacturer name — Kit catalog (cleaned from ''Norrøna'')'),
  (public.profile_norm('Northwave'), 'Northwave', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('NS Bikes'), 'NS Bikes', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Nukeproof'), 'Nukeproof', 'held', 'manufacturer name — EMTB, Kit, MTB catalogs'),
  (public.profile_norm('ONeal'), 'ONeal', 'held', 'manufacturer name — Kit catalog (cleaned from ''O''''Neal'')'),
  (public.profile_norm('Oakley'), 'Oakley', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('OC Mountain Control'), 'OC Mountain Control', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Octane One'), 'Octane One', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('ODI'), 'ODI', 'held', 'manufacturer name — BMX, MTB catalogs'),
  (public.profile_norm('Odyssey'), 'Odyssey', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Ohlins'), 'Ohlins', 'held', 'manufacturer name — MTB catalog (cleaned from ''Öhlins'')'),
  (public.profile_norm('OneUp'), 'OneUp', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Onoff'), 'Onoff', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Onyx'), 'Onyx', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Onza'), 'Onza', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Open'), 'Open', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Optic Nerve'), 'Optic Nerve', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('OQUO'), 'OQUO', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Orange'), 'Orange', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Orbea'), 'Orbea', 'held', 'manufacturer name — EMTB, Gravel, MTB catalogs'),
  (public.profile_norm('Origin8'), 'Origin8', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Otso'), 'Otso', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Panaracer'), 'Panaracer', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Patagonia'), 'Patagonia', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Pearl iZUMi'), 'Pearl iZUMi', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Pipedream'), 'Pipedream', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Pirelli'), 'Pirelli', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Pivot'), 'Pivot', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('PMG'), 'PMG', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('PNW'), 'PNW', 'held', 'manufacturer name — Gravel, Kit, MTB catalogs'),
  (public.profile_norm('POC'), 'POC', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Polygon'), 'Polygon', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Post Moderne'), 'Post Moderne', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Praxis'), 'Praxis', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Praxis Works'), 'Praxis Works', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Premium'), 'Premium', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Prevelo'), 'Prevelo', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Primo'), 'Primo', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Privateer'), 'Privateer', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('PRO'), 'PRO', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Production Privee'), 'Production Privee', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Profile Racing'), 'Profile Racing', 'held', 'manufacturer name — BMX, MTB catalogs'),
  (public.profile_norm('Prologo'), 'Prologo', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Propain'), 'Propain', 'held', 'manufacturer name — EMTB, MTB, Striders catalogs'),
  (public.profile_norm('ProTaper'), 'ProTaper', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Prowheel'), 'Prowheel', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Puky'), 'Puky', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Push'), 'Push', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('RAAW'), 'RAAW', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Race Face'), 'Race Face', 'held', 'manufacturer name — Kit, MTB catalogs'),
  (public.profile_norm('Radio Bikes'), 'Radio Bikes', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Radio Flyer'), 'Radio Flyer', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Radon'), 'Radon', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('Ragley'), 'Ragley', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Redline'), 'Redline', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Rene Herse'), 'Rene Herse', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Renthal'), 'Renthal', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Reserve'), 'Reserve', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Retrospec'), 'Retrospec', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Revel'), 'Revel', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Reverse'), 'Reverse', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Reynolds'), 'Reynolds', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Ride Concepts'), 'Ride Concepts', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Ridley'), 'Ridley', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Ritchey'), 'Ritchey', 'held', 'manufacturer name — Gravel, Road catalogs'),
  (public.profile_norm('RockShox'), 'RockShox', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Rocky Mountain'), 'Rocky Mountain', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('Rondo'), 'Rondo', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Rose'), 'Rose', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Roval'), 'Roval', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Royal Racing'), 'Royal Racing', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Rudy Project'), 'Rudy Project', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Ryders Eyewear'), 'Ryders Eyewear', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Salice'), 'Salice', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Salsa'), 'Salsa', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Salt'), 'Salt', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Samox'), 'Samox', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Santa Cruz'), 'Santa Cruz', 'held', 'manufacturer name — EMTB, Gravel, MTB catalogs'),
  (public.profile_norm('Schwalbe'), 'Schwalbe', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Schwinn'), 'Schwinn', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Scott'), 'Scott', 'held', 'manufacturer name — EMTB, Gravel, Kit, MTB catalogs'),
  (public.profile_norm('SDG'), 'SDG', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Selle Italia'), 'Selle Italia', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Selle Royal'), 'Selle Royal', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Selle San Marco'), 'Selle San Marco', 'held', 'manufacturer name — MTB, Road catalogs'),
  (public.profile_norm('Sensus'), 'Sensus', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Shimano'), 'Shimano', 'held', 'manufacturer name — Gravel, Kit, MTB, Road catalogs'),
  (public.profile_norm('Sidi'), 'Sidi', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Sixpack'), 'Sixpack', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Sixpack Racing'), 'Sixpack Racing', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('SixSixOne'), 'SixSixOne', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Smith'), 'Smith', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Sombrio'), 'Sombrio', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Sonder'), 'Sonder', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Spank'), 'Spank', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Specialized'), 'Specialized', 'held', 'manufacturer name — EMTB, Gravel, Kit, MTB, Road, Striders catalogs'),
  (public.profile_norm('Spy Optic'), 'Spy Optic', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('SQlab'), 'SQlab', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('SR Suntour'), 'SR Suntour', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('SRAM'), 'SRAM', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Standard Byke Co'), 'Standard Byke Co', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Standert'), 'Standert', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Stans'), 'Stans', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Stanton'), 'Stanton', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Starling'), 'Starling', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('State Bicycle Co'), 'State Bicycle Co', 'held', 'manufacturer name — Gravel catalog (cleaned from ''State Bicycle Co.'')'),
  (public.profile_norm('Stolen'), 'Stolen', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Straitline'), 'Straitline', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Stranger Bikes'), 'Stranger Bikes', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Strider'), 'Strider', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Subrosa'), 'Subrosa', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Sun Ringle'), 'Sun Ringle', 'held', 'manufacturer name — MTB catalog (cleaned from ''Sun Ringlé'')'),
  (public.profile_norm('Sunday'), 'Sunday', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('SunRace'), 'SunRace', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('SUNringle'), 'SUNringle', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Supacaz'), 'Supacaz', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Supercross BMX'), 'Supercross BMX', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Surly'), 'Surly', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Sweet Protection'), 'Sweet Protection', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Syncros'), 'Syncros', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('TAG Metals'), 'TAG Metals', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Tektro'), 'Tektro', 'held', 'manufacturer name — BMX, MTB catalogs'),
  (public.profile_norm('Teravail'), 'Teravail', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Terrene'), 'Terrene', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Terry'), 'Terry', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('The Shadow Conspiracy'), 'The Shadow Conspiracy', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Thomson'), 'Thomson', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Tifosi'), 'Tifosi', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Time'), 'Time', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('Title'), 'Title', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Token'), 'Token', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Torege'), 'Torege', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Total BMX'), 'Total BMX', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Transition'), 'Transition', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('TranzX'), 'TranzX', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Trek'), 'Trek', 'held', 'manufacturer name — EMTB, Gravel, MTB, Road catalogs'),
  (public.profile_norm('Trickstuff'), 'Trickstuff', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Troy Lee Designs'), 'Troy Lee Designs', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('TRP'), 'TRP', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Truvativ'), 'Truvativ', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('TSG'), 'TSG', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('TwinWorks'), 'TwinWorks', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('United'), 'United', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Unno'), 'Unno', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Urge'), 'Urge', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Uvex'), 'Uvex', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Vaude'), 'Vaude', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Vee'), 'Vee', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Vee Rubber'), 'Vee Rubber', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Vee Tire Co'), 'Vee Tire Co', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Velo'), 'Velo', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Verde'), 'Verde', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Vittoria'), 'Vittoria', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Vitus'), 'Vitus', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('Von Zipper'), 'Von Zipper', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('VP Components'), 'VP Components', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Wahoo'), 'Wahoo', 'held', 'manufacturer name — Road catalog'),
  (public.profile_norm('We Are One'), 'We Are One', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Wellgo'), 'Wellgo', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('WeThePeople'), 'WeThePeople', 'held', 'manufacturer name — BMX catalog'),
  (public.profile_norm('Wheels Manufacturing'), 'Wheels Manufacturing', 'held', 'manufacturer name — Gravel catalog'),
  (public.profile_norm('Wheels Mfg'), 'Wheels Mfg', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Whisky Parts Co'), 'Whisky Parts Co', 'held', 'manufacturer name — Gravel catalog (cleaned from ''Whisky Parts Co.'')'),
  (public.profile_norm('White Industries'), 'White Industries', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Whyte'), 'Whyte', 'held', 'manufacturer name — EMTB, MTB catalogs'),
  (public.profile_norm('Wishbone'), 'Wishbone', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Wolf Tooth'), 'Wolf Tooth', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('woom'), 'woom', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('WTB'), 'WTB', 'held', 'manufacturer name — Gravel, MTB catalogs'),
  (public.profile_norm('X-Fusion'), 'X-Fusion', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('XLC'), 'XLC', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Xpedo'), 'Xpedo', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('YBN'), 'YBN', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Yedoo'), 'Yedoo', 'held', 'manufacturer name — Striders catalog'),
  (public.profile_norm('Yeti'), 'Yeti', 'held', 'manufacturer name — MTB catalog'),
  (public.profile_norm('Yeti Cycles'), 'Yeti Cycles', 'held', 'manufacturer name — Kit catalog'),
  (public.profile_norm('Zipp'), 'Zipp', 'held', 'manufacturer name — Gravel, MTB, Road catalogs'),
  (public.profile_norm('Zoic'), 'Zoic', 'held', 'manufacturer name — Kit catalog')
on conflict (norm) do nothing;

-- ===========================================================================
-- BATCH 2 — 2026-07-21 (owner order): prominent MTB/cycling YouTube
-- creators/influencers. Both the channel/brand name AND the person's real
-- name are reserved separately when they differ; a self-titled channel (the
-- creator's real name IS the channel name) gets one row. Every real name
-- below was confirmed on a FETCHED page (channel/creator bio, an interview,
-- a published profile, or the creator's own site/LinkedIn) — never guessed.
--
-- Starting points named by the owner: Berm Peak / Seth Alvo (+ the former
-- channel name "Seth's Bike Hacks", shape-cleaned to "Seths Bike Hacks") and
-- Skills With Phil / Phil Kmetz. Remaining names researched from that tier
-- (Fabio Wibmer, Danny MacAskill, Sam Pilgrim, Matt Jones, Ben Cathro, Remy
-- Metailler, BKXC/Brian Kennedy, Singletrack Sampler, Nate Hills, Rob
-- Warner, Christina Chappetta, Eliot Jackson, The Loam Wolf/Drew Rohde, and
-- GMBN's current official presenter roster).
--
-- Skipped (reported, not fabricated):
--   * Singletrack Sampler's real name — search engines surfaced "Alexander
--     Bowers" via an Instagram tag, but no page I could actually fetch
--     (Instagram bio, the channel's Pinkbike page, its About page) confirmed
--     it in his own words. Only the channel name is reserved.
--   * GCN (Global Cycling Network) — the owner's "GMBN/GCN" note covered
--     both; GCN is road-focused and its presenter roster wasn't researched
--     for this pass, so only the "GCN" brand token itself is reserved here.
--   * Rémy Métailler transliterated to "Remy Metailler" (diacritics are
--     illegal in the profiles CHECK shape), same convention as batch 1.
-- ===========================================================================
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('Berm Peak'), 'Berm Peak', 'held', 'influencer — Berm Peak, freehub.com'),
  (public.profile_norm('Seth Alvo'), 'Seth Alvo', 'held', 'influencer — Berm Peak, freehub.com'),
  (public.profile_norm('Seths Bike Hacks'), 'Seths Bike Hacks', 'held', 'influencer — Berm Peak (former channel name, cleaned from ''Seth''''s Bike Hacks''), youthmotivator4life.com'),
  (public.profile_norm('Skills With Phil'), 'Skills With Phil', 'held', 'influencer — Skills With Phil, philkmetz.com'),
  (public.profile_norm('Phil Kmetz'), 'Phil Kmetz', 'held', 'influencer — Skills With Phil, philkmetz.com'),
  (public.profile_norm('BKXC'), 'BKXC', 'held', 'influencer — BKXC, cyclinguptodate.com'),
  (public.profile_norm('Brian Kennedy'), 'Brian Kennedy', 'held', 'influencer — BKXC, cyclinguptodate.com'),
  (public.profile_norm('Fabio Wibmer'), 'Fabio Wibmer', 'held', 'influencer — Fabio Wibmer, en.wikipedia.org'),
  (public.profile_norm('Danny MacAskill'), 'Danny MacAskill', 'held', 'influencer — Danny MacAskill, en.wikipedia.org'),
  (public.profile_norm('Sam Pilgrim'), 'Sam Pilgrim', 'held', 'influencer — Sam Pilgrim, en.wikipedia.org'),
  (public.profile_norm('Matt Jones'), 'Matt Jones', 'held', 'influencer — Matt Jones, muc-off.com'),
  (public.profile_norm('Ben Cathro'), 'Ben Cathro', 'held', 'influencer — Ben Cathro, vitalmtb.com'),
  (public.profile_norm('Remy Metailler'), 'Remy Metailler', 'held', 'influencer — Remy Metailler RAW (cleaned from ''Remy Metailler'' with accents), singletracks.com'),
  (public.profile_norm('Nate Hills'), 'Nate Hills', 'held', 'influencer — Nate Hills, yeticycles.com'),
  (public.profile_norm('Rob Warner'), 'Rob Warner', 'held', 'influencer — Rob Warner, en.wikipedia.org'),
  (public.profile_norm('Christina Chappetta'), 'Christina Chappetta', 'held', 'influencer — Pinkbike presenter, tagcycling.com'),
  (public.profile_norm('Eliot Jackson'), 'Eliot Jackson', 'held', 'influencer — Red Bull TV presenter, singletracks.com'),
  (public.profile_norm('Singletrack Sampler'), 'Singletrack Sampler', 'held', 'influencer — The Singletrack Sampler, pinkbike.com (real name unconfirmed by any fetched page — see worker report)'),
  (public.profile_norm('The Loam Wolf'), 'The Loam Wolf', 'held', 'influencer — The Loam Wolf, theloamwolf.com'),
  (public.profile_norm('Drew Rohde'), 'Drew Rohde', 'held', 'influencer — The Loam Wolf founder, theloamwolf.com'),
  (public.profile_norm('GMBN'), 'GMBN', 'held', 'influencer — Global Mountain Bike Network, gmbn.com'),
  (public.profile_norm('Martyn Ashton'), 'Martyn Ashton', 'held', 'influencer — GMBN presenter, gmbn.com'),
  (public.profile_norm('Rich Payne'), 'Rich Payne', 'held', 'influencer — GMBN presenter, gmbn.com'),
  (public.profile_norm('Ferg Ryan'), 'Ferg Ryan', 'held', 'influencer — GMBN presenter, gmbn.com'),
  (public.profile_norm('James Pickering'), 'James Pickering', 'held', 'influencer — GMBN presenter, gmbn.com'),
  (public.profile_norm('Owen Coutts'), 'Owen Coutts', 'held', 'influencer — GMBN Tech presenter, gmbn.com'),
  (public.profile_norm('Adam Scroxton'), 'Adam Scroxton', 'held', 'influencer — GMBN Tech presenter, gmbn.com'),
  (public.profile_norm('GCN'), 'GCN', 'held', 'influencer — Global Cycling Network (brand token only; presenter roster not researched this pass)')
on conflict (norm) do nothing;

-- ===========================================================================
-- BATCH 3 — 2026-07-21 (owner's local add): Sploosh MTB.
--
-- The rider's real name was NOT included: no page I could actually fetch
-- (YouTube channel/about, Instagram bio, MBR's own MTB-YouTuber roundup)
-- surfaced it — Sploosh MTB is a small local channel with a thin public
-- footprint, and both the YouTube and Instagram pages returned JS shells
-- with no bio text visible to a fetch. Per standing doctrine, a guessed
-- real name is worse than a missing one, so it's skipped and reported
-- rather than fabricated.
-- ===========================================================================
insert into public.reserved_usernames (norm, label, kind, note) values
  (public.profile_norm('Sploosh MTB'), 'Sploosh MTB', 'held', 'influencer — Sploosh MTB, owner order'),
  (public.profile_norm('Sploosh'), 'Sploosh', 'held', 'influencer — Sploosh MTB, owner order')
on conflict (norm) do nothing;
